import unittest

from uncertainty.word import *


class WordsTestCase(unittest.TestCase):
    def test_get_features(self):
        data = [
                ('Its', 'it', 'PRP$', 'B-np'),
                ('short', 'short', 'JJ', 'I-np'),
                ('life', 'life', 'NN', 'I-np'),
                ('span', 'span', 'NN', 'I-np'),
                ('(', '', '-LRB-', 'O'),
                ('thirty-odd', 'thirtyodd', 'JJ', 'B-np'),
                ('episodes', 'episod', 'NNS', 'I-np'),
                (')', '', '-RRB-', 'O'),
                ('was', 'wa', 'VBD', 'B-vp'),
                ('in', 'in', 'IN', 'B-pp'),
                ('part', 'part', 'NN', 'B-np'),
                ('because', 'becaus', 'IN', 'B-sbar'),
                ('it', 'it', 'PRP', 'B-np'),
                ('was', 'wa', 'VBD', 'B-vp'),
                ('considered', 'consid', 'VBN', 'I-vp'),
                ('too', 'too', 'SO', 'B-adjp'),
                ('violent', 'violent', 'JJ', 'I-adjp'),
                ('at', 'at', 'IN', 'B-pp'),
                ('the', 'the', 'DT', 'B-np'),
                ('time', 'time', 'NN', 'I-np'),
                (',', '', ',', 'O'),
                ('although', 'although', 'IN', 'B-sbar'),
                ('the', 'the', 'DT', 'B-np'),
                ('violence', 'violenc', 'NN', 'I-np'),
                ('it', 'it', 'PRP', 'O'),
                ('depicted', 'depict', 'VBN', 'B-vp'),
                ('is', 'is', 'VBZ', 'O'),
                ('actually', 'actual', 'RB', 'B-advp'),
                ('mild', 'mild', 'JJ', 'B-np'),
                ('by', 'by', 'IN', 'B-pp'),
                ('today\'s', 'todai', 'NNS', 'B-np'),
                ('television', 'televi', 'NN', 'I-np'),
                ('standards', 'standard', 'NNS', 'I-np'),
                ('.', '', '.', 'O'),
            ]

        expected = [
                {
                    'pattern_prefix_A': 1.0,
                    'pattern_0_Aa': 1.0,
                    'chunk_2_I-np': 1.0,
                    'chunk_0_B-np': 1.0,
                    'chunk_1_I-np': 1.0,
                    'pattern_1_a': 1.0,
                    'pos_0_PRP$': 1.0,
                    'pos_1_JJ': 1.0,
                    'pos_2_NN': 1.0,
                    'R_0_it_C_0_B-np': 1.0,
                    'root_0_it': 1.0,
                    'prefix_3_Its': 1.0,
                    'prefix_4_Its': 1.0,
                    'prefix_5_Its': 1.0,
                    'suffix_3_Its': 1.0,
                    'suffix_4_Its': 1.0,
                    'suffix_5_Its': 1.0,
                    'R_1_short_C_0_B-np': 1.0,
                    'R_0_it_P_0_PRP$': 1.0,
                    'R_1_short_P_0_PRP$': 1.0,
                    'root_1_short': 1.0,
                    'root_2_life': 1.0
                },
                {
                    'pattern_-1_Aa': 1.0,
                    'chunk_2_I-np': 1.0,
                    'chunk_1_I-np': 1.0,
                    'chunk_-1_B-np': 1.0,
                    'chunk_0_I-np': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pos_2_NN': 1.0,
                    'pos_-1_PRP$': 1.0,
                    'pos_0_JJ': 1.0,
                    'pos_1_NN': 1.0,
                    'suffix_3_ort': 1.0,
                    'root_-1_it': 1.0,
                    'prefix_3_sho': 1.0,
                    'prefix_4_shor': 1.0,
                    'prefix_5_short': 1.0,
                    'suffix_4_hort': 1.0,
                    'suffix_5_short': 1.0,
                    'R_0_short_C_0_I-np': 1.0,
                    'R_-1_it_C_0_I-np': 1.0,
                    'R_0_short_C_0_I-np': 1.0,
                    'R_1_life_C_0_I-np': 1.0,
                    'R_-1_it_P_0_JJ': 1.0,
                    'R_0_short_P_0_JJ': 1.0,
                    'R_1_life_P_0_JJ': 1.0,
                    'root_0_short': 1.0,
                    'root_1_life': 1.0,
                    'root_2_span': 1.0
                },
                {
                    'root_2_': 1.0,
                    'chunk_1_I-np': 1.0,
                    'chunk_0_I-np': 1.0,
                    'chunk_-2_B-np': 1.0,
                    'chunk_-1_I-np': 1.0,
                    'chunk_2_O': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_NN': 1.0,
                    'pos_-2_PRP$': 1.0,
                    'pos_-1_JJ': 1.0,
                    'pos_0_NN': 1.0,
                    'pos_2_-LRB-': 1.0,
                    'root_-2_it': 1.0,
                    'R_-1_short_C_0_I-np': 1.0,
                    'R_0_life_C_0_I-np': 1.0,
                    'prefix_3_lif': 1.0,
                    'prefix_4_life': 1.0,
                    'prefix_5_life': 1.0,
                    'suffix_3_ife': 1.0,
                    'suffix_4_life': 1.0,
                    'suffix_5_life': 1.0,
                    'R_0_life_C_0_I-np': 1.0,
                    'R_1_span_C_0_I-np': 1.0,
                    'R_-1_short_P_0_NN': 1.0,
                    'R_0_life_P_0_NN': 1.0,
                    'R_1_span_P_0_NN': 1.0,
                    'root_-1_short': 1.0,
                    'root_0_life': 1.0,
                    'root_1_span': 1.0
                },
                {
                    'chunk_1_O': 1.0,
                    'R_1__C_0_I-np': 1.0,
                    'root_1_': 1.0,
                    'chunk_0_I-np': 1.0,
                    'pattern_1_!': 1.0,
                    'chunk_-1_I-np': 1.0,
                    'chunk_-2_I-np': 1.0,
                    'chunk_2_B-np': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pos_2_JJ': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_0_NN': 1.0,
                    'pos_-2_JJ': 1.0,
                    'pos_-1_NN': 1.0,
                    'R_1__P_0_NN': 1.0,
                    'pos_1_-LRB-': 1.0,
                    'R_-1_life_C_0_I-np': 1.0,
                    'R_0_span_C_0_I-np': 1.0,
                    'R_-1_life_P_0_NN': 1.0,
                    'R_0_span_P_0_NN': 1.0,
                    'prefix_3_spa': 1.0,
                    'prefix_4_span': 1.0,
                    'prefix_5_span': 1.0,
                    'suffix_3_pan': 1.0,
                    'suffix_4_span': 1.0,
                    'suffix_5_span': 1.0,
                    'R_0_span_C_0_I-np': 1.0,
                    'root_-2_short': 1.0,
                    'root_-1_life': 1.0,
                    'root_0_span': 1.0,
                    'root_2_thirtyodd': 1.0
                },
                {
                    'chunk_0_O': 1.0,
                    'chunk_1_B-np': 1.0,
                    'chunk_2_I-np': 1.0,
                    'root_0_': 1.0,
                    'chunk_-1_I-np': 1.0,
                    'pattern_prefix_!': 1.0,
                    'pattern_0_!': 1.0,
                    'chunk_-2_I-np': 1.0,
                    'R_0__C_0_O': 1.0,
                    'R_0__C_0_O': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_JJ': 1.0,
                    'pos_-1_NN': 1.0,
                    'pos_-2_NN': 1.0,
                    'prefix_3_(': 1.0,
                    'prefix_4_(': 1.0,
                    'prefix_5_(': 1.0,
                    'suffix_3_(': 1.0,
                    'suffix_4_(': 1.0,
                    'suffix_5_(': 1.0,
                    'R_0__P_0_-LRB-': 1.0,
                    'pos_0_-LRB-': 1.0,
                    'pos_2_NNS': 1.0,
                    'pattern_1_a!a': 1.0,
                    'R_-1_span_C_0_O': 1.0,
                    'R_1_thirtyodd_C_0_O': 1.0,
                    'R_-1_span_P_0_-LRB-': 1.0,
                    'R_1_thirtyodd_P_0_-LRB-': 1.0,
                    'root_-2_life': 1.0,
                    'root_-1_span': 1.0,
                    'root_1_thirtyodd': 1.0,
                    'root_2_episod': 1.0
                },
                {
                    'chunk_-1_O': 1.0,
                    'root_2_': 1.0,
                    'chunk_0_B-np': 1.0,
                    'chunk_1_I-np': 1.0,
                    'chunk_2_O': 1.0,
                    'root_-1_': 1.0,
                    'chunk_-2_I-np': 1.0,
                    'pattern_-1_!': 1.0,
                    'R_-1__C_0_B-np': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pos_0_JJ': 1.0,
                    'pos_-2_NN': 1.0,
                    'prefix_3_thi': 1.0,
                    'pos_2_-RRB-': 1.0,
                    'pos_-1_-LRB-': 1.0,
                    'pos_1_NNS': 1.0,
                    'R_-1__P_0_JJ': 1.0,
                    'pattern_0_a!a': 1.0,
                    'prefix_4_thir': 1.0,
                    'prefix_5_thirt': 1.0,
                    'suffix_3_odd': 1.0,
                    'suffix_4_-odd': 1.0,
                    'suffix_5_y-odd': 1.0,
                    'R_0_thirtyodd_C_0_B-np': 1.0,
                    'R_0_thirtyodd_C_0_B-np': 1.0,
                    'R_1_episod_C_0_B-np': 1.0,
                    'R_0_thirtyodd_P_0_JJ': 1.0,
                    'R_1_episod_P_0_JJ': 1.0,
                    'root_-2_span': 1.0,
                    'root_0_thirtyodd': 1.0,
                    'root_1_episod': 1.0
                },
                {
                    'chunk_1_O': 1.0,
                    'R_1__C_0_I-np': 1.0,
                    'root_1_': 1.0,
                    'chunk_-1_B-np': 1.0,
                    'chunk_0_I-np': 1.0,
                    'pattern_1_!': 1.0,
                    'root_-2_': 1.0,
                    'chunk_2_B-vp': 1.0,
                    'chunk_-2_O': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pos_-1_JJ': 1.0,
                    'pos_2_VBD': 1.0,
                    'root_2_wa': 1.0,
                    'pos_0_NNS': 1.0,
                    'pos_1_-RRB-': 1.0,
                    'pos_-2_-LRB-': 1.0,
                    'R_1__P_0_NNS': 1.0,
                    'pattern_-1_a!a': 1.0,
                    'prefix_3_epi': 1.0,
                    'prefix_4_epis': 1.0,
                    'prefix_5_episo': 1.0,
                    'suffix_3_des': 1.0,
                    'suffix_4_odes': 1.0,
                    'suffix_5_sodes': 1.0,
                    'R_0_episod_C_0_I-np': 1.0,
                    'R_-1_thirtyodd_C_0_I-np': 1.0,
                    'R_0_episod_C_0_I-np': 1.0,
                    'R_-1_thirtyodd_P_0_NNS': 1.0,
                    'R_0_episod_P_0_NNS': 1.0,
                    'root_-1_thirtyodd': 1.0,
                    'root_0_episod': 1.0
                },
                {
                    'chunk_0_O': 1.0,
                    'root_0_': 1.0,
                    'chunk_-2_B-np': 1.0,
                    'chunk_-1_I-np': 1.0,
                    'pattern_prefix_!': 1.0,
                    'pattern_0_!': 1.0,
                    'R_0__C_0_O': 1.0,
                    'R_0__C_0_O': 1.0,
                    'chunk_1_B-vp': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_2_IN': 1.0,
                    'chunk_2_B-pp': 1.0,
                    'pos_-2_JJ': 1.0,
                    'root_2_in': 1.0,
                    'pos_1_VBD': 1.0,
                    'root_1_wa': 1.0,
                    'pos_-1_NNS': 1.0,
                    'prefix_3_)': 1.0,
                    'prefix_4_)': 1.0,
                    'prefix_5_)': 1.0,
                    'suffix_3_)': 1.0,
                    'suffix_4_)': 1.0,
                    'suffix_5_)': 1.0,
                    'R_0__P_0_-RRB-': 1.0,
                    'pos_0_-RRB-': 1.0,
                    'R_1_wa_C_0_O': 1.0,
                    'R_-1_episod_C_0_O': 1.0,
                    'R_-1_episod_P_0_-RRB-': 1.0,
                    'R_1_wa_P_0_-RRB-': 1.0,
                    'root_-2_thirtyodd': 1.0,
                    'root_-1_episod': 1.0
                },
                {
                    'chunk_-1_O': 1.0,
                    'root_-1_': 1.0,
                    'chunk_-2_I-np': 1.0,
                    'chunk_2_B-np': 1.0,
                    'pattern_-1_!': 1.0,
                    'pattern_1_a': 1.0,
                    'chunk_0_B-vp': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pos_2_NN': 1.0,
                    'pos_1_IN': 1.0,
                    'chunk_1_B-pp': 1.0,
                    'root_1_in': 1.0,
                    'R_-1__C_0_B-vp': 1.0,
                    'R_-1__P_0_VBD': 1.0,
                    'pos_0_VBD': 1.0,
                    'prefix_3_was': 1.0,
                    'prefix_4_was': 1.0,
                    'prefix_5_was': 1.0,
                    'suffix_3_was': 1.0,
                    'suffix_4_was': 1.0,
                    'suffix_5_was': 1.0,
                    'R_0_wa_C_0_B-vp': 1.0,
                    'R_0_wa_C_0_B-vp': 1.0,
                    'R_0_wa_P_0_VBD': 1.0,
                    'root_0_wa': 1.0,
                    'pos_-2_NNS': 1.0,
                    'pos_-1_-RRB-': 1.0,
                    'R_1_in_C_0_B-vp': 1.0,
                    'R_1_in_P_0_VBD': 1.0,
                    'root_2_part': 1.0,
                    'root_-2_episod': 1.0
                },
                {
                    'pos_0_IN': 1.0,
                    'chunk_0_B-pp': 1.0,
                    'chunk_1_B-np': 1.0,
                    'root_-2_': 1.0,
                    'pattern_1_a': 1.0,
                    'chunk_-2_O': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'chunk_-1_B-vp': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_NN': 1.0,
                    'pos_2_IN': 1.0,
                    'prefix_3_in': 1.0,
                    'prefix_4_in': 1.0,
                    'prefix_5_in': 1.0,
                    'suffix_3_in': 1.0,
                    'suffix_4_in': 1.0,
                    'suffix_5_in': 1.0,
                    'R_0_in_C_0_B-pp': 1.0,
                    'R_0_in_C_0_B-pp': 1.0,
                    'R_0_in_P_0_IN': 1.0,
                    'root_0_in': 1.0,
                    'pos_-1_VBD': 1.0,
                    'root_-1_wa': 1.0,
                    'pos_-2_-RRB-': 1.0,
                    'R_1_part_C_0_B-pp': 1.0,
                    'R_1_part_P_0_IN': 1.0,
                    'root_1_part': 1.0,
                    'R_-1_wa_C_0_B-pp': 1.0,
                    'R_-1_wa_P_0_IN': 1.0,
                    'root_2_becaus': 1.0,
                    'chunk_2_B-sbar': 1.0
                },
                {
                    'pos_-1_IN': 1.0,
                    'chunk_-1_B-pp': 1.0,
                    'chunk_0_B-np': 1.0,
                    'chunk_2_B-np': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'chunk_-2_B-vp': 1.0,
                    'pos_0_NN': 1.0,
                    'pos_1_IN': 1.0,
                    'R_-1_in_P_0_NN': 1.0,
                    'R_-1_in_C_0_B-np': 1.0,
                    'root_-1_in': 1.0,
                    'pos_-2_VBD': 1.0,
                    'pos_2_PRP': 1.0,
                    'root_-2_wa': 1.0,
                    'prefix_3_par': 1.0,
                    'prefix_4_part': 1.0,
                    'R_0_part_C_0_B-np': 1.0,
                    'R_0_part_C_0_B-np': 1.0,
                    'root_0_part': 1.0,
                    'root_2_it': 1.0,
                    'prefix_5_part': 1.0,
                    'suffix_3_art': 1.0,
                    'suffix_4_part': 1.0,
                    'suffix_5_part': 1.0,
                    'R_1_becaus_C_0_B-np': 1.0,
                    'R_0_part_P_0_NN': 1.0,
                    'R_1_becaus_P_0_NN': 1.0,
                    'root_1_becaus': 1.0,
                    'chunk_1_B-sbar': 1.0
                },
                {
                    'pos_0_IN': 1.0,
                    'chunk_1_B-np': 1.0,
                    'pos_-2_IN': 1.0,
                    'chunk_-2_B-pp': 1.0,
                    'chunk_-1_B-np': 1.0,
                    'chunk_2_B-vp': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_-1_NN': 1.0,
                    'root_-2_in': 1.0,
                    'pos_2_VBD': 1.0,
                    'root_2_wa': 1.0,
                    'pos_1_PRP': 1.0,
                    'R_-1_part_P_0_IN': 1.0,
                    'root_-1_part': 1.0,
                    'root_1_it': 1.0,
                    'suffix_3_use': 1.0,
                    'prefix_3_bec': 1.0,
                    'prefix_4_beca': 1.0,
                    'prefix_5_becau': 1.0,
                    'suffix_4_ause': 1.0,
                    'suffix_5_cause': 1.0,
                    'R_0_becaus_C_0_B-sbar': 1.0,
                    'R_-1_part_C_0_B-sbar': 1.0,
                    'R_0_becaus_C_0_B-sbar': 1.0,
                    'R_1_it_C_0_B-sbar': 1.0,
                    'R_0_becaus_P_0_IN': 1.0,
                    'R_1_it_P_0_IN': 1.0,
                    'root_0_becaus': 1.0,
                    'chunk_0_B-sbar': 1.0
                },
                {
                    'pos_-1_IN': 1.0,
                    'chunk_0_B-np': 1.0,
                    'chunk_-2_B-np': 1.0,
                    'chunk_1_B-vp': 1.0,
                    'chunk_2_I-vp': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_-2_NN': 1.0,
                    'pos_2_VBN': 1.0,
                    'pos_1_VBD': 1.0,
                    'R_1_wa_C_0_B-np': 1.0,
                    'R_1_wa_P_0_PRP': 1.0,
                    'root_1_wa': 1.0,
                    'pos_0_PRP': 1.0,
                    'root_-2_part': 1.0,
                    'prefix_3_it': 1.0,
                    'prefix_4_it': 1.0,
                    'prefix_5_it': 1.0,
                    'suffix_3_it': 1.0,
                    'suffix_4_it': 1.0,
                    'suffix_5_it': 1.0,
                    'R_0_it_C_0_B-np': 1.0,
                    'R_0_it_C_0_B-np': 1.0,
                    'R_0_it_P_0_PRP': 1.0,
                    'root_0_it': 1.0,
                    'R_-1_becaus_C_0_B-np': 1.0,
                    'R_-1_becaus_P_0_PRP': 1.0,
                    'root_-1_becaus': 1.0,
                    'root_2_consid': 1.0,
                    'chunk_-1_B-sbar': 1.0
                },
                {
                    'pos_-2_IN': 1.0,
                    'chunk_-1_B-np': 1.0,
                    'pattern_1_a': 1.0,
                    'chunk_0_B-vp': 1.0,
                    'chunk_1_I-vp': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_VBN': 1.0,
                    'pos_0_VBD': 1.0,
                    'prefix_3_was': 1.0,
                    'prefix_4_was': 1.0,
                    'prefix_5_was': 1.0,
                    'suffix_3_was': 1.0,
                    'suffix_4_was': 1.0,
                    'suffix_5_was': 1.0,
                    'R_0_wa_C_0_B-vp': 1.0,
                    'R_0_wa_C_0_B-vp': 1.0,
                    'R_0_wa_P_0_VBD': 1.0,
                    'root_0_wa': 1.0,
                    'pos_-1_PRP': 1.0,
                    'chunk_2_B-adjp': 1.0,
                    'root_2_too': 1.0,
                    'R_-1_it_C_0_B-vp': 1.0,
                    'R_-1_it_P_0_VBD': 1.0,
                    'root_-1_it': 1.0,
                    'R_1_consid_C_0_B-vp': 1.0,
                    'R_1_consid_P_0_VBD': 1.0,
                    'root_-2_becaus': 1.0,
                    'root_1_consid': 1.0,
                    'pos_2_SO': 1.0,
                    'chunk_-2_B-sbar': 1.0
                },
                {
                    'chunk_-2_B-np': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pos_2_JJ': 1.0,
                    'chunk_-1_B-vp': 1.0,
                    'chunk_0_I-vp': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_0_VBN': 1.0,
                    'pos_-1_VBD': 1.0,
                    'R_-1_wa_C_0_I-vp': 1.0,
                    'R_-1_wa_P_0_VBN': 1.0,
                    'root_-1_wa': 1.0,
                    'pos_-2_PRP': 1.0,
                    'chunk_1_B-adjp': 1.0,
                    'chunk_2_I-adjp': 1.0,
                    'prefix_3_con': 1.0,
                    'prefix_4_cons': 1.0,
                    'suffix_3_red': 1.0,
                    'root_1_too': 1.0,
                    'root_-2_it': 1.0,
                    'prefix_5_consi': 1.0,
                    'suffix_4_ered': 1.0,
                    'suffix_5_dered': 1.0,
                    'R_0_consid_C_0_I-vp': 1.0,
                    'R_0_consid_C_0_I-vp': 1.0,
                    'R_1_too_C_0_I-vp': 1.0,
                    'R_0_consid_P_0_VBN': 1.0,
                    'R_1_too_P_0_VBN': 1.0,
                    'root_0_consid': 1.0,
                    'root_2_violent': 1.0,
                    'pos_1_SO': 1.0
                },
                {
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_JJ': 1.0,
                    'chunk_-2_B-vp': 1.0,
                    'chunk_-1_I-vp': 1.0,
                    'root_2_at': 1.0,
                    'pos_2_IN': 1.0,
                    'chunk_2_B-pp': 1.0,
                    'pos_-1_VBN': 1.0,
                    'pos_-2_VBD': 1.0,
                    'root_-2_wa': 1.0,
                    'chunk_0_B-adjp': 1.0,
                    'chunk_1_I-adjp': 1.0,
                    'prefix_3_too': 1.0,
                    'prefix_4_too': 1.0,
                    'prefix_5_too': 1.0,
                    'suffix_3_too': 1.0,
                    'suffix_4_too': 1.0,
                    'suffix_5_too': 1.0,
                    'root_0_too': 1.0,
                    'R_0_too_C_0_B-adjp': 1.0,
                    'R_-1_consid_C_0_B-adjp': 1.0,
                    'R_0_too_C_0_B-adjp': 1.0,
                    'R_1_violent_C_0_B-adjp': 1.0,
                    'R_-1_consid_P_0_SO': 1.0,
                    'R_0_too_P_0_SO': 1.0,
                    'R_1_violent_P_0_SO': 1.0,
                    'root_-1_consid': 1.0,
                    'root_1_violent': 1.0,
                    'pos_0_SO': 1.0
                },
                {
                    'chunk_2_B-np': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_0_JJ': 1.0,
                    'chunk_-2_I-vp': 1.0,
                    'root_1_at': 1.0,
                    'pos_1_IN': 1.0,
                    'chunk_1_B-pp': 1.0,
                    'pos_2_DT': 1.0,
                    'root_2_the': 1.0,
                    'pos_-2_VBN': 1.0,
                    'chunk_-1_B-adjp': 1.0,
                    'chunk_0_I-adjp': 1.0,
                    'suffix_3_ent': 1.0,
                    'root_-1_too': 1.0,
                    'prefix_3_vio': 1.0,
                    'prefix_4_viol': 1.0,
                    'prefix_5_viole': 1.0,
                    'suffix_4_lent': 1.0,
                    'suffix_5_olent': 1.0,
                    'R_0_violent_C_0_I-adjp': 1.0,
                    'R_-1_too_C_0_I-adjp': 1.0,
                    'R_0_violent_C_0_I-adjp': 1.0,
                    'R_1_at_C_0_I-adjp': 1.0,
                    'R_-1_too_P_0_JJ': 1.0,
                    'R_0_violent_P_0_JJ': 1.0,
                    'R_1_at_P_0_JJ': 1.0,
                    'root_-2_consid': 1.0,
                    'root_0_violent': 1.0,
                    'pos_-1_SO': 1.0
                },
                {
                    'pos_0_IN': 1.0,
                    'chunk_0_B-pp': 1.0,
                    'chunk_1_B-np': 1.0,
                    'chunk_2_I-np': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_2_NN': 1.0,
                    'pos_-1_JJ': 1.0,
                    'prefix_3_at': 1.0,
                    'prefix_4_at': 1.0,
                    'prefix_5_at': 1.0,
                    'suffix_3_at': 1.0,
                    'suffix_4_at': 1.0,
                    'suffix_5_at': 1.0,
                    'R_0_at_C_0_B-pp': 1.0,
                    'R_0_at_C_0_B-pp': 1.0,
                    'R_0_at_P_0_IN': 1.0,
                    'root_0_at': 1.0,
                    'pos_1_DT': 1.0,
                    'root_1_the': 1.0,
                    'R_1_the_C_0_B-pp': 1.0,
                    'R_1_the_P_0_IN': 1.0,
                    'chunk_-2_B-adjp': 1.0,
                    'chunk_-1_I-adjp': 1.0,
                    'root_-2_too': 1.0,
                    'R_-1_violent_C_0_B-pp': 1.0,
                    'R_-1_violent_P_0_IN': 1.0,
                    'root_-1_violent': 1.0,
                    'root_2_time': 1.0,
                    'pos_-2_SO': 1.0
                },
                {
                    'root_2_': 1.0,
                    'pos_-1_IN': 1.0,
                    'pos_2_,': 1.0,
                    'chunk_-1_B-pp': 1.0,
                    'chunk_0_B-np': 1.0,
                    'chunk_1_I-np': 1.0,
                    'chunk_2_O': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_NN': 1.0,
                    'pos_-2_JJ': 1.0,
                    'root_-1_at': 1.0,
                    'pos_0_DT': 1.0,
                    'prefix_3_the': 1.0,
                    'prefix_4_the': 1.0,
                    'prefix_5_the': 1.0,
                    'suffix_3_the': 1.0,
                    'suffix_4_the': 1.0,
                    'suffix_5_the': 1.0,
                    'R_0_the_C_0_B-np': 1.0,
                    'R_0_the_C_0_B-np': 1.0,
                    'R_0_the_P_0_DT': 1.0,
                    'root_0_the': 1.0,
                    'R_-1_at_C_0_B-np': 1.0,
                    'R_-1_at_P_0_DT': 1.0,
                    'chunk_-2_I-adjp': 1.0,
                    'R_1_time_C_0_B-np': 1.0,
                    'R_1_time_P_0_DT': 1.0,
                    'root_-2_violent': 1.0,
                    'root_1_time': 1.0
                },
                {
                    'chunk_1_O': 1.0,
                    'R_1__C_0_I-np': 1.0,
                    'root_1_': 1.0,
                    'pos_-2_IN': 1.0,
                    'pos_1_,': 1.0,
                    'chunk_-2_B-pp': 1.0,
                    'chunk_-1_B-np': 1.0,
                    'chunk_0_I-np': 1.0,
                    'pattern_1_!': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_2_IN': 1.0,
                    'pos_0_NN': 1.0,
                    'root_-2_at': 1.0,
                    'pos_-1_DT': 1.0,
                    'R_-1_the_C_0_I-np': 1.0,
                    'root_-1_the': 1.0,
                    'R_-1_the_P_0_NN': 1.0,
                    'R_1__P_0_NN': 1.0,
                    'chunk_2_B-sbar': 1.0,
                    'prefix_3_tim': 1.0,
                    'prefix_4_time': 1.0,
                    'prefix_5_time': 1.0,
                    'suffix_3_ime': 1.0,
                    'suffix_4_time': 1.0,
                    'suffix_5_time': 1.0,
                    'R_0_time_C_0_I-np': 1.0,
                    'R_0_time_C_0_I-np': 1.0,
                    'R_0_time_P_0_NN': 1.0,
                    'root_0_time': 1.0,
                    'root_2_although': 1.0
                },
                {
                    'chunk_0_O': 1.0,
                    'prefix_3_,': 1.0,
                    'prefix_4_,': 1.0,
                    'prefix_5_,': 1.0,
                    'suffix_3_,': 1.0,
                    'suffix_4_,': 1.0,
                    'suffix_5_,': 1.0,
                    'R_0__P_0_,': 1.0,
                    'root_0_': 1.0,
                    'pos_0_,': 1.0,
                    'chunk_-2_B-np': 1.0,
                    'chunk_-1_I-np': 1.0,
                    'pattern_prefix_!': 1.0,
                    'pattern_0_!': 1.0,
                    'chunk_2_B-np': 1.0,
                    'R_0__C_0_O': 1.0,
                    'R_0__C_0_O': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_IN': 1.0,
                    'pos_-1_NN': 1.0,
                    'pos_2_DT': 1.0,
                    'pos_-2_DT': 1.0,
                    'root_2_the': 1.0,
                    'root_-2_the': 1.0,
                    'chunk_1_B-sbar': 1.0,
                    'R_-1_time_C_0_O': 1.0,
                    'R_1_although_C_0_O': 1.0,
                    'R_-1_time_P_0_,': 1.0,
                    'R_1_although_P_0_,': 1.0,
                    'root_-1_time': 1.0,
                    'root_1_although': 1.0
                },
                {
                    'chunk_-1_O': 1.0,
                    'pos_0_IN': 1.0,
                    'chunk_1_B-np': 1.0,
                    'chunk_2_I-np': 1.0,
                    'root_-1_': 1.0,
                    'pos_-1_,': 1.0,
                    'chunk_-2_I-np': 1.0,
                    'pattern_-1_!': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pos_2_NN': 1.0,
                    'pos_-2_NN': 1.0,
                    'pos_1_DT': 1.0,
                    'root_1_the': 1.0,
                    'R_1_the_P_0_IN': 1.0,
                    'R_-1__P_0_IN': 1.0,
                    'chunk_0_B-sbar': 1.0,
                    'prefix_3_alt': 1.0,
                    'prefix_4_alth': 1.0,
                    'prefix_5_altho': 1.0,
                    'suffix_3_ugh': 1.0,
                    'suffix_4_ough': 1.0,
                    'suffix_5_hough': 1.0,
                    'R_0_although_C_0_B-sbar': 1.0,
                    'R_-1__C_0_B-sbar': 1.0,
                    'R_0_although_C_0_B-sbar': 1.0,
                    'R_1_the_C_0_B-sbar': 1.0,
                    'R_0_although_P_0_IN': 1.0,
                    'root_-2_time': 1.0,
                    'root_0_although': 1.0,
                    'root_2_violenc': 1.0
                },
                {
                    'pos_-1_IN': 1.0,
                    'chunk_0_B-np': 1.0,
                    'chunk_1_I-np': 1.0,
                    'chunk_2_O': 1.0,
                    'root_-2_': 1.0,
                    'pos_-2_,': 1.0,
                    'pattern_1_a': 1.0,
                    'chunk_-2_O': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_NN': 1.0,
                    'pos_0_DT': 1.0,
                    'prefix_3_the': 1.0,
                    'prefix_4_the': 1.0,
                    'prefix_5_the': 1.0,
                    'suffix_3_the': 1.0,
                    'suffix_4_the': 1.0,
                    'suffix_5_the': 1.0,
                    'R_0_the_C_0_B-np': 1.0,
                    'R_0_the_C_0_B-np': 1.0,
                    'R_0_the_P_0_DT': 1.0,
                    'root_0_the': 1.0,
                    'pos_2_PRP': 1.0,
                    'root_2_it': 1.0,
                    'chunk_-1_B-sbar': 1.0,
                    'R_-1_although_C_0_B-np': 1.0,
                    'R_1_violenc_C_0_B-np': 1.0,
                    'R_-1_although_P_0_DT': 1.0,
                    'R_1_violenc_P_0_DT': 1.0,
                    'root_-1_although': 1.0,
                    'root_1_violenc': 1.0
                },
                {
                    'chunk_1_O': 1.0,
                    'pos_-2_IN': 1.0,
                    'chunk_-1_B-np': 1.0,
                    'chunk_0_I-np': 1.0,
                    'chunk_2_B-vp': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_0_NN': 1.0,
                    'pos_-1_DT': 1.0,
                    'pos_2_VBN': 1.0,
                    'R_-1_the_C_0_I-np': 1.0,
                    'root_-1_the': 1.0,
                    'R_-1_the_P_0_NN': 1.0,
                    'pos_1_PRP': 1.0,
                    'root_1_it': 1.0,
                    'suffix_3_nce': 1.0,
                    'R_1_it_C_0_I-np': 1.0,
                    'chunk_-2_B-sbar': 1.0,
                    'prefix_3_vio': 1.0,
                    'prefix_4_viol': 1.0,
                    'prefix_5_viole': 1.0,
                    'suffix_4_ence': 1.0,
                    'suffix_5_lence': 1.0,
                    'R_0_violenc_C_0_I-np': 1.0,
                    'R_0_violenc_C_0_I-np': 1.0,
                    'R_0_violenc_P_0_NN': 1.0,
                    'R_1_it_P_0_NN': 1.0,
                    'root_-2_although': 1.0,
                    'root_0_violenc': 1.0,
                    'root_2_depict': 1.0
                },
                {
                    'chunk_0_O': 1.0,
                    'chunk_-2_B-np': 1.0,
                    'chunk_-1_I-np': 1.0,
                    'chunk_2_O': 1.0,
                    'chunk_1_B-vp': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_-1_NN': 1.0,
                    'pos_-2_DT': 1.0,
                    'pos_1_VBN': 1.0,
                    'root_-2_the': 1.0,
                    'pos_0_PRP': 1.0,
                    'pos_2_VBZ': 1.0,
                    'R_0_it_C_0_O': 1.0,
                    'prefix_3_it': 1.0,
                    'prefix_4_it': 1.0,
                    'prefix_5_it': 1.0,
                    'suffix_3_it': 1.0,
                    'suffix_4_it': 1.0,
                    'suffix_5_it': 1.0,
                    'R_0_it_P_0_PRP': 1.0,
                    'root_0_it': 1.0,
                    'R_0_it_C_0_O': 1.0,
                    'R_-1_violenc_C_0_O': 1.0,
                    'R_1_depict_C_0_O': 1.0,
                    'R_-1_violenc_P_0_PRP': 1.0,
                    'R_1_depict_P_0_PRP': 1.0,
                    'root_-1_violenc': 1.0,
                    'root_1_depict': 1.0,
                    'root_2_is': 1.0
                },
                {
                    'chunk_1_O': 1.0,
                    'chunk_-1_O': 1.0,
                    'chunk_-2_I-np': 1.0,
                    'pattern_1_a': 1.0,
                    'chunk_0_B-vp': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_-2_NN': 1.0,
                    'pos_0_VBN': 1.0,
                    'pos_2_RB': 1.0,
                    'chunk_2_B-advp': 1.0,
                    'pos_-1_PRP': 1.0,
                    'pos_1_VBZ': 1.0,
                    'suffix_3_ted': 1.0,
                    'R_-1_it_C_0_B-vp': 1.0,
                    'root_-1_it': 1.0,
                    'prefix_3_dep': 1.0,
                    'prefix_4_depi': 1.0,
                    'prefix_5_depic': 1.0,
                    'suffix_4_cted': 1.0,
                    'suffix_5_icted': 1.0,
                    'R_0_depict_C_0_B-vp': 1.0,
                    'R_0_depict_C_0_B-vp': 1.0,
                    'R_1_is_C_0_B-vp': 1.0,
                    'R_-1_it_P_0_VBN': 1.0,
                    'R_0_depict_P_0_VBN': 1.0,
                    'R_1_is_P_0_VBN': 1.0,
                    'root_-2_violenc': 1.0,
                    'root_0_depict': 1.0,
                    'root_1_is': 1.0,
                    'root_2_actual': 1.0
                },
                {
                    'chunk_0_O': 1.0,
                    'chunk_2_B-np': 1.0,
                    'pattern_1_a': 1.0,
                    'chunk_-2_O': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pos_2_JJ': 1.0,
                    'chunk_-1_B-vp': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_-1_VBN': 1.0,
                    'pos_1_RB': 1.0,
                    'chunk_1_B-advp': 1.0,
                    'pos_-2_PRP': 1.0,
                    'pos_0_VBZ': 1.0,
                    'root_-2_it': 1.0,
                    'R_-1_depict_C_0_O': 1.0,
                    'prefix_3_is': 1.0,
                    'prefix_4_is': 1.0,
                    'prefix_5_is': 1.0,
                    'suffix_3_is': 1.0,
                    'suffix_4_is': 1.0,
                    'suffix_5_is': 1.0,
                    'R_0_is_C_0_O': 1.0,
                    'R_0_is_C_0_O': 1.0,
                    'R_1_actual_C_0_O': 1.0,
                    'R_-1_depict_P_0_VBZ': 1.0,
                    'R_0_is_P_0_VBZ': 1.0,
                    'R_1_actual_P_0_VBZ': 1.0,
                    'root_-1_depict': 1.0,
                    'root_0_is': 1.0,
                    'root_1_actual': 1.0,
                    'root_2_mild': 1.0
                },
                {
                    'chunk_-1_O': 1.0,
                    'chunk_1_B-np': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_JJ': 1.0,
                    'chunk_-2_B-vp': 1.0,
                    'pos_2_IN': 1.0,
                    'chunk_2_B-pp': 1.0,
                    'root_2_by': 1.0,
                    'pos_-2_VBN': 1.0,
                    'pos_0_RB': 1.0,
                    'chunk_0_B-advp': 1.0,
                    'pos_-1_VBZ': 1.0,
                    'prefix_3_act': 1.0,
                    'prefix_4_actu': 1.0,
                    'prefix_5_actua': 1.0,
                    'suffix_3_lly': 1.0,
                    'suffix_4_ally': 1.0,
                    'suffix_5_ually': 1.0,
                    'R_0_actual_C_0_B-advp': 1.0,
                    'R_-1_is_C_0_B-advp': 1.0,
                    'R_0_actual_C_0_B-advp': 1.0,
                    'R_1_mild_C_0_B-advp': 1.0,
                    'R_-1_is_P_0_RB': 1.0,
                    'R_0_actual_P_0_RB': 1.0,
                    'R_1_mild_P_0_RB': 1.0,
                    'root_-2_depict': 1.0,
                    'root_-1_is': 1.0,
                    'root_0_actual': 1.0,
                    'root_1_mild': 1.0
                },
                {
                    'chunk_0_B-np': 1.0,
                    'chunk_2_B-np': 1.0,
                    'pattern_1_a': 1.0,
                    'chunk_-2_O': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_0_JJ': 1.0,
                    'pos_1_IN': 1.0,
                    'chunk_1_B-pp': 1.0,
                    'root_1_by': 1.0,
                    'pos_-1_RB': 1.0,
                    'chunk_-1_B-advp': 1.0,
                    'R_1_by_C_0_B-np': 1.0,
                    'pos_2_NNS': 1.0,
                    'pos_-2_VBZ': 1.0,
                    'prefix_3_mil': 1.0,
                    'prefix_4_mild': 1.0,
                    'prefix_5_mild': 1.0,
                    'suffix_3_ild': 1.0,
                    'suffix_4_mild': 1.0,
                    'suffix_5_mild': 1.0,
                    'R_0_mild_C_0_B-np': 1.0,
                    'R_-1_actual_C_0_B-np': 1.0,
                    'R_0_mild_C_0_B-np': 1.0,
                    'R_-1_actual_P_0_JJ': 1.0,
                    'R_0_mild_P_0_JJ': 1.0,
                    'R_1_by_P_0_JJ': 1.0,
                    'root_-2_is': 1.0,
                    'root_-1_actual': 1.0,
                    'root_0_mild': 1.0,
                    'root_2_todai': 1.0
                },
                {
                    'pos_0_IN': 1.0,
                    'chunk_0_B-pp': 1.0,
                    'chunk_1_B-np': 1.0,
                    'chunk_2_I-np': 1.0,
                    'chunk_-1_B-np': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_2_NN': 1.0,
                    'pos_-1_JJ': 1.0,
                    'prefix_3_by': 1.0,
                    'prefix_4_by': 1.0,
                    'prefix_5_by': 1.0,
                    'suffix_3_by': 1.0,
                    'suffix_4_by': 1.0,
                    'suffix_5_by': 1.0,
                    'R_0_by_C_0_B-pp': 1.0,
                    'R_0_by_C_0_B-pp': 1.0,
                    'R_0_by_P_0_IN': 1.0,
                    'root_0_by': 1.0,
                    'pos_-2_RB': 1.0,
                    'chunk_-2_B-advp': 1.0,
                    'pos_1_NNS': 1.0,
                    'pattern_1_a!a': 1.0,
                    'R_-1_mild_C_0_B-pp': 1.0,
                    'R_1_todai_C_0_B-pp': 1.0,
                    'R_-1_mild_P_0_IN': 1.0,
                    'R_1_todai_P_0_IN': 1.0,
                    'root_-2_actual': 1.0,
                    'root_-1_mild': 1.0,
                    'root_1_todai': 1.0,
                    'root_2_televi': 1.0
                },
                {
                    'chunk_2_I-np': 1.0,
                    'pos_-1_IN': 1.0,
                    'chunk_-1_B-pp': 1.0,
                    'chunk_0_B-np': 1.0,
                    'chunk_1_I-np': 1.0,
                    'chunk_-2_B-np': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_1_NN': 1.0,
                    'pos_-2_JJ': 1.0,
                    'root_-1_by': 1.0,
                    'R_-1_by_C_0_B-np': 1.0,
                    'pos_0_NNS': 1.0,
                    'pos_2_NNS': 1.0,
                    "suffix_3_y's": 1.0,
                    'pattern_0_a!a': 1.0,
                    'prefix_3_tod': 1.0,
                    'prefix_4_toda': 1.0,
                    'prefix_5_today': 1.0,
                    "suffix_4_ay's": 1.0,
                    "suffix_5_day's": 1.0,
                    'R_0_todai_C_0_B-np': 1.0,
                    'R_0_todai_C_0_B-np': 1.0,
                    'R_1_televi_C_0_B-np': 1.0,
                    'R_-1_by_P_0_NNS': 1.0,
                    'R_0_todai_P_0_NNS': 1.0,
                    'R_1_televi_P_0_NNS': 1.0,
                    'root_-2_mild': 1.0,
                    'root_0_todai': 1.0,
                    'root_1_televi': 1.0,
                    'root_2_standard': 1.0
                },
                {
                    'root_2_': 1.0,
                    'chunk_1_I-np': 1.0,
                    'pos_-2_IN': 1.0,
                    'chunk_-2_B-pp': 1.0,
                    'chunk_-1_B-np': 1.0,
                    'chunk_0_I-np': 1.0,
                    'chunk_2_O': 1.0,
                    'pattern_1_a': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pos_0_NN': 1.0,
                    'root_-2_by': 1.0,
                    'suffix_3_ion': 1.0,
                    'suffix_4_sion': 1.0,
                    'suffix_5_ision': 1.0,
                    'pos_2_.': 1.0,
                    'pos_-1_NNS': 1.0,
                    'pos_1_NNS': 1.0,
                    'pattern_-1_a!a': 1.0,
                    'prefix_3_tel': 1.0,
                    'prefix_4_tele': 1.0,
                    'prefix_5_telev': 1.0,
                    'R_0_televi_C_0_I-np': 1.0,
                    'R_-1_todai_C_0_I-np': 1.0,
                    'R_0_televi_C_0_I-np': 1.0,
                    'R_1_standard_C_0_I-np': 1.0,
                    'R_-1_todai_P_0_NN': 1.0,
                    'R_0_televi_P_0_NN': 1.0,
                    'R_1_standard_P_0_NN': 1.0,
                    'root_-1_todai': 1.0,
                    'root_0_televi': 1.0,
                    'root_1_standard': 1.0
                },
                {
                    'chunk_1_O': 1.0,
                    'R_1__C_0_I-np': 1.0,
                    'root_1_': 1.0,
                    'chunk_0_I-np': 1.0,
                    'pattern_1_!': 1.0,
                    'chunk_-2_B-np': 1.0,
                    'chunk_-1_I-np': 1.0,
                    'pattern_prefix_a': 1.0,
                    'pattern_0_a': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_-1_NN': 1.0,
                    'pos_1_.': 1.0,
                    'pos_0_NNS': 1.0,
                    'pos_-2_NNS': 1.0,
                    'R_1__P_0_NNS': 1.0,
                    'suffix_3_rds': 1.0,
                    'R_-1_televi_P_0_NNS': 1.0,
                    'R_-1_televi_C_0_I-np': 1.0,
                    'R_0_standard_C_0_I-np': 1.0,
                    'prefix_3_sta': 1.0,
                    'prefix_4_stan': 1.0,
                    'prefix_5_stand': 1.0,
                    'suffix_4_ards': 1.0,
                    'suffix_5_dards': 1.0,
                    'R_0_standard_C_0_I-np': 1.0,
                    'R_0_standard_P_0_NNS': 1.0,
                    'root_-2_todai': 1.0,
                    'root_-1_televi': 1.0,
                    'root_0_standard': 1.0
                },
                {
                    'chunk_0_O': 1.0,
                    'root_0_': 1.0,
                    'chunk_-1_I-np': 1.0,
                    'pattern_prefix_!': 1.0,
                    'pattern_0_!': 1.0,
                    'chunk_-2_I-np': 1.0,
                    'R_0__C_0_O': 1.0,
                    'R_0__C_0_O': 1.0,
                    'pattern_-1_a': 1.0,
                    'pos_-2_NN': 1.0,
                    'prefix_3_.': 1.0,
                    'prefix_4_.': 1.0,
                    'prefix_5_.': 1.0,
                    'suffix_3_.': 1.0,
                    'suffix_4_.': 1.0,
                    'suffix_5_.': 1.0,
                    'R_0__P_0_.': 1.0,
                    'pos_0_.': 1.0,
                    'pos_-1_NNS': 1.0,
                    'R_-1_standard_C_0_O': 1.0,
                    'R_-1_standard_P_0_.': 1.0,
                    'root_-2_televi': 1.0,
                    'root_-1_standard': 1.0
                },
            ]

        words = Words.from_groups(data)
        actual = words.get_features()

        self.maxDiff = None

        for i in range(0, len(expected)):
            self.assertCountEqual(
                    expected[i], actual[i], msg='Index: {}'.format(i)
                )
